PassGenius/PassGenius/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('generate/', include('generate.urls')),
]

PassGenius/generate/urls.py
from django.urls import path

from . import views

app_name = 'generate'

urlpatterns = [
    path('', views.generate, name='generate'),
]

PassGenius/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

PassGenius/generate/models.py
from django.db import models

# Create your models here.

PassGenius/homepage/models.py
from django.db import models

# Create your models here.

PassGenius/generate/views.py
from django.shortcuts import render

from random import choice
chars = '!&$#?@abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'


def generate(request):
    template = 'generate/generate.html'
    password = ''
    for i in range(6):
        if i == 3:
            password += str(choice(range(0,9)))
        password += choice(chars)

    context = {
        'password': password
    }

    return render(request, template, context)

PassGenius/homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, template_name='homepage/index.html')


def about(request):
    return render(request, template_name='homepage/about.html')

PassGenius/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body style="background-image: url({% static 'img/back.png' %}); background-size: cover;">	   
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

PassGenius/templates/generate/generate.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid d-flex h-100 justify-content-center align-items-center p-5">
    <form class="row g-3">
      <div class="col-auto">
        <input class="form-control" type="text" value="{{ password }}" aria-label="Disabled input example" disabled readonly>
      </div>
      <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Сгенерировать</button>
      </div>
    </form>
  </div>
{% endblock content %}

PassGenius/templates/homepage/about.html
{% extends 'base.html' %}

{% block content %}
  <p><h1>О проекте</h1></p>
  <br>
  <p>
    <b>
      PassGenius - это мощное и интуитивно понятное веб-приложение, 
      созданное для генерации надежных и непроницаемых паролей. В современном мире безопасности данных, 
      защита вашей информации на высшем уровне - это необходимость, и PassGenius поможет вам в этом.
    </b>
  </p>  
{% endblock content %}

PassGenius/templates/homepage/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="text-center">
    <p><h1><b>Приветствую тебя дорогой друг!</b></h1></p>
    <p></h2><b>Это генератор паролей</b></h2></p>
    <a href='{% url "generate:generate" %}'>
      <button type="button" class="btn btn-warning">
      Перейти к генерации
    </button>
    </a>
  </div>
{% endblock content %}

PassGenius/templates/includes/footer.html
<footer class="text-center py-3 fixed-bottom">
  <p class="text-white" ><b>© Ivan_Dev</b></p>    
</footer>

PassGenius/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
  <header>
    <div class="container py-3">
      <ul class="nav justify-content-center">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'homepage:index' %} active {% endif %}" aria-current="page" href="{% url 'homepage:index' %}">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'homepage:about' %} active {% endif %}" href="{% url 'homepage:about' %}">О проекте</a>
        </ul>
      </ul>
    </div>
  </header>
{% endwith %}